v3.11.10

diff --git a/ind b/ind
--- a/ind
+++ b/ind
@@ -4,8 +4,8 @@
 
 # See ChangeLog for changes.
 
-[ $(uname) = 'Darwin' ] && [ ! $(which gdate) ] && echo "$(basename $0): 'coreutils' is required." && exit 1
-[ $(uname) = 'Darwin' ] && [ ! $(which gsed)  ] && echo "$(basename $0): 'GNU sed' is required." && exit 1
+[ $(uname) = 'Darwin' ] && [ ! $(which gdate) ] && echo "$(basename $0): 'coreutils' is required."	&& exit 1
+[ $(uname) = 'Darwin' ] && [ ! $(which gsed)  ] && echo "$(basename $0): 'GNU sed' is required."	&& exit 1
 
 GITREP=$HOME/src/ind
 HOLTMP=/tmp/ind_holidays
@@ -43,6 +43,8 @@ mktconvert=1118 # Anno Ordinis; 1118 CE
 jiyconvert=660	# Japanese Imperial year; 660 BCE
 chiconvert=2697	# Chinese Lunar year, 21 January to 20 February; 2698 BCE
 rocconvert=1911 # ROC year; 1912 CE
+
+frcconvert=1792 # French Revolutionary Calendar; 1792 CE
 
 budconvert=543	# Buddhist Era or Thai Solar year; 543 BCE
 
@@ -351,6 +353,11 @@ else unset HEBREW; fi
 (( julp=year+jupconvert ))
 (( buddhist=year+budconvert ))
 
+# French Revolutionary Calendar
+(( frc=year-frcconvert ))
+[ $frc -le 0 ] && unset frc
+[ $(which rnum) ] && [ $frc ] && frc=$(rnum $frc)
+
 # Roman & Byzantine calendars are aligned to Julian calendar
 (( rome=year+romconvert ))
 [[ 10#$jdoy -ge 1 ]] && (( rome+=1 )) # January 1st (Day 1)
@@ -404,53 +411,56 @@ if [ $COMMON ]; then
 	[ $REGNUM -eq 0 ] && REGDATE="$month/$day" && REGYEAR=$year
 	regdt=$(date -d"${REGDATE[$REGNUM]}" +%-j)
 	[ $year -eq ${REGYEAR[$REGNUM]} ] && [[ 10#$doy -lt 10#$regdt ]] && (( REGNUM-=1 ))
-	[ $REGNUM -gt 0 ] && (( reg=$year-${REGYEAR[REGNUM]} )) || reg=0
-	[[ 10#$doy -ge 10#$regdt ]] && (( reg+=1 ))
+	if [ $REGNUM -gt 0 ]; then
+		(( reg=$year-${REGYEAR[REGNUM]} ))
+		[[ 10#$doy -ge 10#$regdt ]] && (( reg+=1 ))
+	else reg=0; fi
+
 	[ $reg -le 0 ] && reg="" || reg="$reg ${REGNAME[10#$REGNUM]}"
 	fi
 
 # main()
 [ $FULLCE ]		&& printf "$bold%s %d %s %d$bold\n" ${DOWL[$dow]} $(( 10#$day )) ${MONTHL[10#$month]} $year
 if [ $COMMON ]; then
-				   printf "$bold"; printf "CE %d %s %s Ind. %s" $year $rnyear $ind "$reg"; echo "$bold"
-				   printf "Day %3d / Week %2d %3s " $doy $iwn $ltz
-	[ $kloc ]	&& printf "%s" "$kloc"; printf "\n"
-	[ $mjd ]	&& printf "MJD %-7s %s UTC " $mjd $(echo ${utc:5:5} |sed 's/-/\//')
-	[ $beat ]	&& printf "%s" $beat; [ $mjd ] || [ $beat ] && printf "\n"
-	[ $tjd ]	&& printf "TJD %-7s" $tjd
-	[ $rdi ]	&& printf "RD  %s " $rdi
-	#[ "$reg" ]	&& printf "/ %s" "$reg"; 
-	[ $tjd ] || [ $rdi ] || $reg && printf "\n"
+				   printf "$bold"; printf "CE %d %s %s Ind." $year $rnyear $ind; echo "$bold"
+				   printf "Day %3d / Week %2d %3s" $doy $iwn $ltz
+	[ $kloc ]	&& printf "%6s" "$kloc";	[ $kloc ]				&& printf "\n"
+	[ $mjd ]	&& printf "MJD %-7s %s UTC" $mjd $(echo ${utc:5:5} |sed 's/-/\//')
+	[ $beat ]	&& printf "%5s" "$beat"; 	[ $mjd ] || [ $beat ]	&& printf "\n"
+	[ $tjd ]	&& printf "TJD %-8s" $tjd
+	[ $rdi ]	&& printf "RD  %-7s" $rdi;	[ $tjd ] || [ $rdi ]	&& printf "\n"
+	[ "$reg" ]	&& printf "%-12s" "$reg"
+	[ $frc ]	&& printf "FRC %-9s" $frc;	[ "$reg" ] || [ $frc ]	&& printf "\n"
 	fi
 
-[ $HHPC ]		&& printf "%-17s H-H %4d\n" "${hhdate::${#hhdate}-5}" ${hhdate:(-4)}
-[ $ERISIAN ]	&& printf "%-16s YOLD %d\n" "${discord::${#discord}-5}" ${discord:(-4)}
-[ $HEBREW ]		&& printf "%-18s AM %d\n" "${hebdate::${#hebdate}-6}" ${hebdate:(-4)}
+[ $HHPC ]		&& printf "%-17s H-H %4d\n"	"${hhdate::${#hhdate}-5}"	${hhdate:(-4)}
+[ $ERISIAN ]	&& printf "%-16s YOLD %d\n"	"${discord::${#discord}-5}"	${discord:(-4)}
+[ $HEBREW ]		&& printf "%-18s AM %d\n"	"${hebdate::${#hebdate}-6}"	${hebdate:(-4)}
 
-[ $ROME ]		&& printf "City of Rome       au %d\n" $rome
-[ $BYZANTINE ]	&& printf "Byzantine %-6s   AM %d\n" $byzind $byzantine
+[ $ROME ]		&& printf "City of Rome       au %d\n"	$rome
+[ $BYZANTINE ]	&& printf "Byzantine %-6s   AM %d\n"	$byzind $byzantine
 
-[ $JULIANP ]	&& printf "Julian Period         %d\n" $julp
+[ $JULIANP ]	&& printf "Julian Period         %d\n"	$julp
 
-[ $MASORETIC ]	&& printf "Anno Lucis %-5s      %d\n" $mgl $masor
-[ $MASORETIC ]	&& printf "Anno R.C.             %d\n" $arc
-[ $MASORETIC ]	&& printf "Anno Inventionis      %d\n" $yod
-[ $MASORETIC ]	&& printf "Anno Ordinis          %4d\n" $mkt
+[ $MASORETIC ]	&& printf "Anno Lucis %-5s      %d\n"	$mgl $masor
+[ $MASORETIC ]	&& printf "Anno R.C.             %d\n"	$arc
+[ $MASORETIC ]	&& printf "Anno Inventionis      %d\n"	$yod
+[ $MASORETIC ]	&& printf "Anno Ordinis          %4d\n"	$mkt
 
-[ $JAPANIY ]	&& printf "Japanese Imp. %-5s   %d\n" "$jen" $jiy
-[ $CHINALY ]	&& printf "Chinese Lunar %-5s   %d\n" "$roc" $cly
-[ $BUDDHIST ]	&& printf "Buddhist Era          %d\n" $buddhist
+[ $JAPANIY ]	&& printf "Japanese Imp. %-5s   %d\n"	"$jen" $jiy
+[ $CHINALY ]	&& printf "Chinese Lunar %-5s   %d\n"	"$roc" $cly
+[ $BUDDHIST ]	&& printf "Buddhist Era          %d\n"	$buddhist
 
 if [ $VERBOSE ]; then
-				   printf "Dominical letter      %s\n" $dominical
-				   printf "Epact                 %s\n" ${EPACTS[$golden]}
-				   printf "Golden number         %s\n" $golden
-				   printf "Equinox               %s\n" ${equinox:5} |sed 's/-/\//'
-				   printf "Julian calendar (%d)  %s\n" $jdelta ${jymd:5:5} |sed 's/-/\//'
+				   printf "Dominical letter      %s\n"	$dominical
+				   printf "Epact                 %s\n"	${EPACTS[$golden]}
+				   printf "Golden number         %s\n"	$golden
+				   printf "Equinox               %s\n"	${equinox:5} |sed 's/-/\//'
+				   printf "Julian calendar (%d)  %s\n"	$jdelta ${jymd:5:5} |sed 's/-/\//'
 				   printf "Julian day of year    %03d\n" $jdoy
-				   printf "Ides                  %d\n" $ides
+				   printf "Ides                  %d\n"	$ides
 
-	[ $_LY ]	&& printf "Leap year             %s\n" $year
+	[ $_LY ]	&& printf "Leap year             %s\n"	$year
 	[ "$moon" ]	&& printf "Phase                 %-17s\n" "$moon"
 	[ "$jen" ]	&& printf "Japanese Era          %s\n" "${ERANAME[10#$ERANUM]}"
 	[ $cny ] 	&& printf "Chinese New Year      %s %s\n" $(echo ${cny:5:5}|sed 's/-/\//') ${ZODIAC[10#$yearof]}
