v3.12.0

diff --git a/mob b/mob
--- a/mob
+++ b/mob
@@ -4,25 +4,24 @@
 
 app=$(basename $0)
 [ $(uname) = 'Darwin' ] && [ ! $(which gdate) ] && echo "$app: 'coreutils' is required." && exit 1
-for i in hebcal ncal; do [ ! $(which $i) ] && echo "$app: '$i' is required." && exit 1; done
+for i in gcal hebcal ncal; do [ ! $(which $i) ] && echo "$app: '$i' is required." && exit 1; done
 
-HEADER=true
+HEADER=
 HEBREW=true
+ISLAMIC=
 PROXIM=true
 ADVENT=
 
 year=$(date +%Y)
-DATEFMT="%d %b"
+DATEFMT="%m/%d" # DATEFMT="%d %b"
 YAHRFILE="$HOME/.calendar/deaths"
 
-while getopts ":cejlYPAy:?" OPTION; do
+while getopts ":eijlYPAy:H?" OPTION; do
 	case $OPTION in
-		c)	# Format for 'calendar'
-			DATEFMT="%m/%d"
-			CFORMAT=true
-			[ $HEADER ] && echo "// Generated by '$(basename $0)'";;
 		e)	# Erevs
 			EREV=true;;
+		i)	# Islamic holidays
+			[ $ISLAMIC ] && unset ISLAMIC || ISLAMIC=true;;
 		j)	# Hebrew holidays
 			[ $HEBREW ] && unset HEBREW || HEBREW=true;;
 		l)	# Holiday information
@@ -46,12 +45,13 @@ while getopts ":cejlYPAy:?" OPTION; do
 
 		y)	# set year
 			year=$OPTARG;;
+		H)	# header
+			[ $HEADER ] && unset HEADER || HEADER=true;;
 
 		*)	getusage $0
 			exit;;
 	esac
 done
-hebyear=$(hebcal -Th 01 01 $year | sed -n 1p | sed 's/.*, //')
 
 function set_hebrew() {
 	exclude="/Shabbat/d;/Ta'anit/d"
@@ -59,6 +59,8 @@ function set_hebrew() {
 	hebtext=$(hebcal -rx $1 $2 |cut -f2 |sed "1d;$exclude;s/ I//;/1 Candle/s/^/Erev /;s/:.*//")
 	dispheb+=$(printf "%s*\t%s|" "$hebdate" "$hebtext")
 }
+hebyear=$(hebcal -Th 01 01 $year | sed -n 1p | sed 's/.*, //')
+[ $HEADER ] && echo "// Generated by '$(basename $0)'"
 
 # Hebrew holidays
 if [ $HEBREW ]; then outp=true
@@ -88,6 +90,11 @@ if [ $HEBREW ]; then outp=true
 			hebcal -ghY $YAHRFILE $year |sed -e 's/^....-..-..\s/$(date -d& +"$DATEFMT")*/' |
 			while read -r line; do eval echo -e "$line" |sed 's/\*/*\t☠ /'; done
 	fi
+fi
+if [ $ISLAMIC ]; then [ $outp ] && echo; outp=true
+	gcal -e --date-format="%1%>02*M/%>02*D%2" --islamic-civil-holidays 2023 |grep --no-messages "(Isl)" |
+	sed -e 's/:\s/*\t/' -e 's/\s*(Isl).*//' -e '/Ramadan/s/$/~/;/Eid-al/s/$/~/;/New Year/s/$/~/' -e "s/'s Day//" |
+	grep --no-messages '~' | sed 's/~$//' | uniq -f1
 fi
 
 # Dates calculated by their proximity to another date
